const types = {
    SET_FAVORITE_LOCATIONS : 'SET_FAVORITE_LOCATIONS',
    SET_WEATHER : 'SET_WEATHER',
    SET_LOCATION_SUGGEST: 'SET_LOCATION_SUGGEST',

    ADD_FAVORITE_LOCATION: 'ADD_FAVORITE_LOCATION',
    REMOVE_FAVORITE_LOCATION: 'REMOVE_FAVORITE_LOCATION',
    
    TOGGLE_IS_FAHRENHEIT: 'TOGGLE_IS_FAHRENHEIT',
    REMOVE_SUGGESTIONS: 'REMOVE_SUGGESTIONS'
    
}

export default types